version: '3.8'

name: animus

services:
  db:
    image: postgres:12.2
    volumes:
      - pg:/data/postgres
    networks:
      net:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

  back:
    image: docker.nexus.jiveoff.fr/efrei-craft/animus:stable
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    networks:
      net:
      rp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.animus.rule=Host(`animus.dev.efreicraft.fr`)"
      - "traefik.http.routers.animus.entrypoints=websecure"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: bureau@efreicraft.fr
      PGADMIN_DEFAULT_PASSWORD: bureaudev
      SCRIPT_NAME: /pgadmin
    volumes:
      - /config/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      net:
      rp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.dev.efreicraft.fr`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.routers.db.entrypoints=websecure"

volumes:
  pg:
    driver: local

networks:
  rp:
    external: true
    name: reverseproxy_nw
  net:

