version: "3.8"

name: animus_dev

services:
  db:
    image: postgres:12.2
    volumes:
      - pg:/data/postgres
    env_file: .env.local
    ports:
      - "5432:5432"

  rest:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: .env.local

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - rest
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env.local

volumes:
  pg:
    driver: local
