version: '3.8'

name: animus

services:
  db:
    image: postgres:12.2
    volumes:
      - pg:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

  back:
    image: docker.nexus.jiveoff.fr/efrei-craft/animus:stable
    command: npm start
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.animus.rule=Host(`animus.dev.efreicraft.fr`)"
      - "traefik.http.routers.animus.entrypoints=websecure"

volumes:
  pg:
    driver: local