version: '3.8'

name: ecapi

services:
  db:
    image: postgres:12.2
    volumes:
      - pg:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

  back:
    image: docker.nexus.jiveoff.fr/efrei-craft/ecapi:latest
    command: npm start
    restart: always
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

volumes:
  pg:
    driver: local