version: '3.8'

name: ecapi

services:
  db:
    image: postgres:12.2
    volumes:
      - pg:/data/postgres
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      net:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

  back:
    image: docker.nexus.jiveoff.fr/efrei-craft/ecapi:stable
    command: npm start
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    networks:
      net:
      rp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ecapi.rule=Host(`ecapi.dev.efreicraft.fr`)"
      - "traefik.http.routers.ecapi.entrypoints=websecure"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: mvt
    networks:
      net:
      rp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host(`db.dev.efreicraft.fr`)"
      - "traefik.http.routers.db.entrypoints=websecure"

volumes:
  pg:
    driver: local

networks:
  rp:
    external: true
    name: reverseproxy_nw
  net:

