FROM node:alpine3.16

WORKDIR /app

COPY package.json package-lock.json ./
COPY package*.json ./

COPY prisma ./prisma/

COPY tsconfig.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

RUN npm prune --omit=dev

EXPOSE 3000

CMD ["npm", "start"]