FROM node:alpine3.16 AS build

WORKDIR /app

COPY . .

RUN ls -la

RUN npm install && npx prisma generate && npm run build

FROM node:alpine3.16 AS production

WORKDIR /app

COPY --from=build /app .

RUN npm install --only=production && npx prisma generate

RUN npm install pm2 -g

EXPOSE 80

CMD ["pm2-runtime", "index.js"]